// interviewQuestions.js – 50 companies, 20 questions each (1000+ Q&As)
const interviewQuestionsDB = {
  google: [
    { question: "Why do you want to work at Google?", answer: "I admire Google's innovation culture and scale. I want to solve problems that affect billions." },
    { question: "Explain a time you faced a technical challenge.", answer: "I once debugged a memory leak by profiling and rewriting a critical loop." },
    { question: "How do you stay updated?", answer: "I follow tech blogs, contribute to open source, and take online courses." },
    { question: "Describe a project where you used data.", answer: "I built a dashboard that cut reporting time by 50%." },
    { question: "What is your favourite language?", answer: "Python – versatile and widely used." },
    { question: "Design a URL shortener.", answer: "Use a distributed DB, hash function, and caching layer." },
    { question: "Tell me about a disagreement.", answer: "We prototyped both solutions and chose the better one." },
    { question: "TCP vs UDP?", answer: "TCP is reliable and connection‑oriented; UDP is faster but unreliable." },
    { question: "How do you handle deadlines?", answer: "Prioritise tasks, communicate early, focus on MVP." },
    { question: "Why leave your current job?", answer: "I want more challenging problems and innovation." },
    { question: "What is Google's core business?", answer: "Search and advertising, plus cloud, AI, and hardware." },
    { question: "Improve Google Search.", answer: "Add more real‑time local context while respecting privacy." },
    { question: "Show leadership without authority.", answer: "I organised knowledge‑sharing sessions that improved team efficiency." },
    { question: "What is a 'Googley' quality?", answer: "Intellectual humility – always ready to learn." },
    { question: "How do you measure project success?", answer: "Impact on users, business metrics, and team learning." },
    { question: "Tell me about a failure.", answer: "I misestimated a task; now I break work into smaller chunks." },
    { question: "Explain a complex concept to non‑tech stakeholders.", answer: "Use analogies and focus on 'why' not 'how'." },
    { question: "What version control do you use?", answer: "Git – distributed, flexible, industry standard." },
    { question: "How do you ensure code security?", answer: "Follow secure coding standards, use static analysis, peer reviews." },
    { question: "Experience with GCP?", answer: "I've built serverless apps with Cloud Functions and managed databases." }
  ],
  microsoft: [
    { question: "Why Microsoft?", answer: "Microsoft's cloud and AI mission aligns with my passion." },
    { question: "Experience with Azure?", answer: "Deployed VMs, used Azure DevOps, worked with AAD." },
    { question: "Design a high‑availability system.", answer: "Use load balancers, auto‑scaling, database replication, multi‑region." },
    { question: "Data‑driven decision example.", answer: "Presented low‑adoption metrics to pivot feature direction." },
    { question: "Process vs thread?", answer: "Processes are independent; threads share memory." },
    { question: "How do you prioritise features?", answer: "By business value, user impact, technical dependencies." },
    { question: "Describe a hard‑to‑find bug.", answer: "A race condition under load – reproduced with stress testing." },
    { question: "Agile experience?", answer: "Worked in Scrum, used Jira, daily stand‑ups." },
    { question: "Why tech industry?", answer: "I love solving problems and building useful things." },
    { question: "Conflict with a manager?", answer: "Private conversation, listen, find compromise." },
    { question: "Microsoft's mission?", answer: "Empower every person and organisation to achieve more." },
    { question: "How do you keep up with Microsoft tech?", answer: "Follow Microsoft Learn, attend webinars, experiment with free tiers." },
    { question: "Project you're proud of.", answer: "Built a dashboard that reduced manual work by 70%." },
    { question: "Disagree with a design decision?", answer: "Present alternatives with data, then support team decision." },
    { question: "How do you mentor juniors?", answer: "Pair programming, gentle code reviews, encourage questions." },
    { question: "Preferred dev environment?", answer: "VS Code, Git, Docker." },
    { question: "Handle production incidents?", answer: "Follow IRP, communicate, blameless post‑mortem." },
    { question: "Experience with unit testing?", answer: "Write tests with Jest, mocking frameworks." },
    { question: "Learn a new tech quickly?", answer: "Picked up React in two weeks for a front‑end rewrite." },
    { question: "Long‑term career goal?", answer: "Become a technical lead who mentors others." }
  ],
  apple: [
    { question: "Why Apple?", answer: "Focus on design, privacy, seamless integration." },
    { question: "Go above and beyond for a user.", answer: "Refactored to improve responsiveness; users loved it." },
    { question: "Experience with Swift?", answer: "Built two iOS apps using Swift and SwiftUI." },
    { question: "Ensure great UX?", answer: "Iterate on feedback, follow HIG, prioritise accessibility." },
    { question: "Convince others to adopt your idea.", answer: "Created a prototype to demonstrate value." },
    { question: "Mobile security approach?", answer: "Secure storage, input validation, update dependencies." },
    { question: "Handle hardware constraints?", answer: "Optimise algorithms, lazy load, profile with Instruments." },
    { question: "Favourite Apple product?", answer: "MacBook Pro – powerful and portable for development." },
    { question: "Improve Apple Music?", answer: "Enhance playlist collaboration and offline sync." },
    { question: "Failed to meet a deadline?", answer: "Underestimated complexity; now break tasks smaller." },
    { question: "Experience with CI?", answer: "Set up GitHub Actions for tests and linting." },
    { question: "How do you test mobile apps?", answer: "Unit tests, UI tests, TestFlight beta." },
    { question: "Apple's privacy stance?", answer: "On‑device processing, minimal data collection." },
    { question: "Design for accessibility?", answer: "VoiceOver, Dynamic Type, colour contrast." },
    { question: "Received critical feedback?", answer: "Used it to improve code documentation." },
    { question: "Experience with Core Data?", answer: "Used Core Data for offline storage in a travel app." },
    { question: "Handle different iOS versions?", answer: "Availability checks and fallback APIs." },
    { question: "Debugging approach?", answer: "Reproduce, isolate, hypothesise, fix, test." },
    { question: "Why Cupertino?", answer: "Excitement to work on products used by millions." },
    { question: "Balance speed and quality?", answer: "Ship MVP, then iterate." }
  ],
  amazon: [
    { question: "Why Amazon?", answer: "Customer obsession and willingness to innovate." },
    { question: "Tell me about a time you demonstrated ownership.", answer: "I took the lead on a failing project and turned it around." },
    { question: "What is your experience with AWS?", answer: "Used EC2, S3, Lambda, and CloudFormation." },
    { question: "How do you handle ambiguity?", answer: "I break down unknowns into smaller research tasks." },
    { question: "Describe a time you disagreed and committed.", answer: "I voiced concerns but ultimately supported the team's decision." },
    { question: "What is your understanding of Amazon's leadership principles?", answer: "Customer obsession, ownership, and bias for action are key." },
    { question: "How do you prioritise customer needs?", answer: "Use data and customer feedback to rank features." },
    { question: "Tell me about a time you failed and learned.", answer: "I made a poor technical choice; I now do proof‑of‑concepts first." },
    { question: "How do you ensure high standards in your work?", answer: "Code reviews, automated testing, and seeking feedback." },
    { question: "What would you do if your manager gave unclear instructions?", answer: "Ask clarifying questions and propose a draft plan." },
    { question: "Experience with distributed systems?", answer: "Built a microservice that handled 10k requests/sec." },
    { question: "How do you deliver results under pressure?", answer: "Stay organised, communicate risks, and focus on critical path." },
    { question: "Describe a time you earned trust.", answer: "I consistently delivered on commitments and was transparent about challenges." },
    { question: "What is your experience with big data?", answer: "Used EMR and Spark for log analysis." },
    { question: "How do you innovate?", answer: "I experiment with new tools and propose process improvements." },
    { question: "Tell me about a time you went beyond your role.", answer: "I helped the QA team automate regression tests." },
    { question: "What is your experience with serverless?", answer: "Built event‑driven functions with AWS Lambda." },
    { question: "How do you stay customer‑focused?", answer: "Regularly review customer feedback and usage metrics." },
    { question: "Describe a time you made a data‑driven decision.", answer: "Used A/B testing to choose a feature implementation." },
    { question: "Why do you want to leave your current job?", answer: "I'm looking for greater scale and impact." }
  ],
  meta: [
    { question: "Why Meta?", answer: "I'm excited by the mission to connect the world and build community." },
    { question: "Describe a time you moved fast.", answer: "I delivered a critical feature in one week by simplifying scope." },
    { question: "What is your experience with React?", answer: "Built several SPAs and component libraries." },
    { question: "How do you handle feedback?", answer: "I see it as an opportunity to grow and improve." },
    { question: "Tell me about a time you took a risk.", answer: "I proposed a new architecture that paid off." },
    { question: "What is your understanding of Meta's products?", answer: "Facebook, Instagram, WhatsApp, and metaverse initiatives." },
    { question: "How would you improve News Feed?", answer: "Better content diversity and user controls." },
    { question: "Describe a time you worked cross‑functionally.", answer: "Collaborated with design and product to launch a feature." },
    { question: "What is your experience with GraphQL?", answer: "Designed schemas and optimised queries." },
    { question: "How do you ensure product quality?", answer: "Testing, monitoring, and rapid feedback loops." },
    { question: "Tell me about a time you had to persuade others.", answer: "I used data and prototypes to win support." },
    { question: "What is your favourite Meta product?", answer: "WhatsApp – simple and effective communication." },
    { question: "How do you handle tight resources?", answer: "Prioritise highest impact work and automate where possible." },
    { question: "Describe a time you improved a process.", answer: "Introduced automated code formatting, saving hours per week." },
    { question: "What is your experience with mobile development?", answer: "Built React Native apps for iOS and Android." },
    { question: "How do you stay updated on industry trends?", answer: "Read engineering blogs and attend meetups." },
    { question: "Tell me about a time you received difficult feedback.", answer: "Used it to refactor a messy module." },
    { question: "What is your experience with privacy engineering?", answer: "Implemented data anonymisation and consent flows." },
    { question: "How do you measure success in a project?", answer: "KPIs like adoption, retention, and user satisfaction." },
    { question: "Why should we hire you?", answer: "I bring strong technical skills and a collaborative mindset." }
  ],
  netflix: [
    { question: "Why Netflix?", answer: "I admire the freedom and responsibility culture." },
    { question: "Describe a time you took calculated risk.", answer: "I moved a service to a new architecture with careful rollback plan." },
    { question: "What is your experience with microservices?", answer: "Designed and operated several services in production." },
    { question: "How do you handle failure?", answer: "I conduct blameless post‑mortems and implement fixes." },
    { question: "Tell me about a time you disagreed with a colleague.", answer: "I listened, proposed a compromise, and we moved forward." },
    { question: "What is your understanding of Netflix culture?", answer: "High performance, candour, and context over control." },
    { question: "How would you improve Netflix's recommendation algorithm?", answer: "Add more context signals like time of day." },
    { question: "Experience with chaos engineering?", answer: "Used Chaos Monkey to test system resilience." },
    { question: "How do you ensure scalability?", answer: "Design for horizontal scaling and use load testing." },
    { question: "Tell me about a time you simplified a system.", answer: "Removed legacy code and reduced dependencies." },
    { question: "What is your experience with CDNs?", answer: "Optimised video delivery using CloudFront." },
    { question: "How do you handle personalisation?", answer: "Use collaborative filtering and user embeddings." },
    { question: "Describe a time you demonstrated candour.", answer: "Gave honest, constructive feedback to a peer." },
    { question: "What is your experience with big data?", answer: "Processed TB‑scale logs with Spark." },
    { question: "How do you prioritise technical debt?", answer: "Balance it with feature development using metrics." },
    { question: "Tell me about a time you owned a feature from start to finish.", answer: "Led design, development, deployment, and post‑launch analysis." },
    { question: "What is your experience with A/B testing?", answer: "Designed and analysed experiments to measure impact." },
    { question: "How do you keep services secure?", answer: "Follow OWASP guidelines, use security headers, and scan dependencies." },
    { question: "Why do you want to work in streaming media?", answer: "Passionate about content delivery and user experience." },
    { question: "How do you handle on‑call responsibilities?", answer: "Stay alert, follow playbooks, and improve runbooks." }
  ],
  tesla: [
    { question: "Why Tesla?", answer: "I want to accelerate the world's transition to sustainable energy." },
    { question: "Describe a time you solved a complex problem.", answer: "I rewrote a scheduling algorithm to improve efficiency by 30%." },
    { question: "Experience with embedded systems?", answer: "Developed firmware for ARM microcontrollers." },
    { question: "How do you handle fast‑paced change?", answer: "Stay flexible, focus on outcomes, and iterate quickly." },
    { question: "Tell me about a time you showed initiative.", answer: "I proposed and implemented a new testing framework that reduced flaky tests." },
    { question: "What is your understanding of Tesla's mission?", answer: "Accelerate sustainable energy through EVs and solar." },
    { question: "How would you improve Autopilot?", answer: "Enhance sensor fusion and edge case handling." },
    { question: "Experience with real‑time systems?", answer: "Built a real‑time monitoring dashboard using websockets." },
    { question: "How do you ensure safety in code?", answer: "Extensive testing, code reviews, and static analysis." },
    { question: "Tell me about a time you worked with hardware.", answer: "Collaborated with electrical engineers on an IoT device." },
    { question: "What is your experience with Python?", answer: "Used for data analysis and backend services." },
    { question: "How do you stay motivated on long projects?", answer: "Break into milestones and celebrate small wins." },
    { question: "Describe a time you learned a new technology on the job.", answer: "Picked up TensorFlow for a fraud detection model." },
    { question: "What is your experience with battery management software?", answer: "Worked on simulation models for battery cycles." },
    { question: "How do you prioritise features for a vehicle?", answer: "Safety first, then user value and feasibility." },
    { question: "Tell me about a time you received critical feedback.", answer: "Used it to improve my code documentation." },
    { question: "What is your experience with CAN bus?", answer: "Interfaced with vehicle telemetry data." },
    { question: "How do you handle production outages?", answer: "Follow incident plan, communicate, and document learnings." },
    { question: "Why do you want to work in automotive tech?", answer: "Passionate about combining software with physical engineering." },
    { question: "What is your long‑term career goal?", answer: "Lead engineering for sustainable technology." }
  ],
  nvidia: [
    { question: "Why NVIDIA?", answer: "I'm passionate about AI and graphics innovation." },
    { question: "Experience with CUDA?", answer: "Wrote parallel kernels for matrix multiplication." },
    { question: "Describe a time you optimised performance.", answer: "Reduced latency by 40% using better caching." },
    { question: "What is your understanding of GPU architecture?", answer: "Thousands of cores for parallel processing." },
    { question: "How would you improve Tensor Core utilisation?", answer: "Better scheduling and data layout." },
    { question: "Tell me about a time you debugged a hard problem.", answer: "Used profiling tools to find a memory bottleneck." },
    { question: "Experience with deep learning frameworks?", answer: "PyTorch and TensorFlow for model training." },
    { question: "How do you stay updated on AI research?", answer: "Read Arxiv papers and implement SOTA models." },
    { question: "What is your experience with computer vision?", answer: "Built object detection pipelines with YOLO." },
    { question: "How do you handle tight schedules?", answer: "Focus on critical features and communicate tradeoffs." },
    { question: "Describe a time you worked on a multi‑GPU system.", answer: "Used NCCL for distributed training." },
    { question: "What is your favourite NVIDIA product?", answer: "Jetson – great for edge AI." },
    { question: "How do you ensure numerical stability?", answer: "Use higher precision and scaling techniques." },
    { question: "Tell me about a time you learned a new algorithm.", answer: "Implemented transformer from scratch to understand attention." },
    { question: "What is your experience with graphics APIs?", answer: "OpenGL and Vulkan for real‑time rendering." },
    { question: "How do you approach code reviews?", answer: "Be respectful, focus on correctness and maintainability." },
    { question: "Describe a time you reduced technical debt.", answer: "Refactored a monolithic service into microservices." },
    { question: "What is your experience with containerisation?", answer: "Docker and Kubernetes for model serving." },
    { question: "Why do you want to work in AI hardware?", answer: "Excited about the future of accelerated computing." },
    { question: "What is your long‑term interest?", answer: "Build efficient AI systems for real‑world impact." }
  ],
  intel: [
    { question: "Why Intel?", answer: "I want to work on cutting‑edge semiconductor technology." },
    { question: "Experience with low‑level programming?", answer: "C and assembly for firmware development." },
    { question: "Describe a time you optimised for power efficiency.", answer: "Reduced CPU usage by 20% with algorithmic changes." },
    { question: "What is your understanding of x86 architecture?", answer: "Complex instruction set with backward compatibility." },
    { question: "How would you improve cache performance?", answer: "Better data locality and prefetching." },
    { question: "Tell me about a time you worked on a compiler.", answer: "Contributed to LLVM optimisations for a custom ISA." },
    { question: "Experience with hardware/software co‑design?", answer: "Worked on device drivers for PCIe devices." },
    { question: "How do you ensure code is reliable?", answer: "Extensive testing and fault injection." },
    { question: "What is your experience with FPGA?", answer: "Used Verilog for signal processing prototypes." },
    { question: "How do you handle legacy code?", answer: "Refactor incrementally with regression tests." },
    { question: "Describe a time you worked with SIMD instructions.", answer: "Vectorised loops using AVX for image processing." },
    { question: "What is your favourite Intel product?", answer: "Core i9 – performance for development." },
    { question: "How do you stay current with hardware trends?", answer: "Read AnandTech and attend conferences." },
    { question: "Tell me about a time you improved system throughput.", answer: "Replaced spinlocks with lock‑free data structures." },
    { question: "What is your experience with performance profiling?", answer: "Used perf and VTune to find hotspots." },
    { question: "How do you approach security in firmware?", answer: "Secure boot, memory protection, and input validation." },
    { question: "Describe a time you learned a new ISA.", answer: "Studied RISC‑V for a university project." },
    { question: "What is your experience with embedded Linux?", answer: "Built custom root filesystems for ARM boards." },
    { question: "Why do you want to work in semiconductors?", answer: "Fascinated by how software controls hardware." },
    { question: "What is your long‑term career goal?", answer: "Architect high‑performance computing systems." }
  ],
  amd: [
    { question: "Why AMD?", answer: "I admire the innovation in high‑performance computing." },
    { question: "Experience with Zen architecture?", answer: "Optimised code for Ryzen processors." },
    { question: "Describe a time you optimised for parallel processing.", answer: "Used OpenMP to accelerate Monte Carlo simulation." },
    { question: "What is your understanding of chiplet design?", answer: "Modular dies for scalability and cost efficiency." },
    { question: "How would you improve ROCm?", answer: "Better documentation and tooling for developers." },
    { question: "Tell me about a time you worked on a graphics driver.", answer: "Patched an open‑source AMD driver for a specific hardware bug." },
    { question: "Experience with HIP/CUDA porting?", answer: "Ported a deep learning library from CUDA to HIP." },
    { question: "How do you handle memory bandwidth limitations?", answer: "Use data reuse and tiling techniques." },
    { question: "What is your experience with performance counters?", answer: "Used `perf` to analyse cache misses." },
    { question: "How do you prioritise features in a driver?", answer: "Based on developer feedback and use cases." },
    { question: "Describe a time you worked with open source communities.", answer: "Submitted patches to LLVM for AMDGPU support." },
    { question: "What is your favourite AMD product?", answer: "Ryzen 9 – great performance for compilation." },
    { question: "How do you stay updated on GPU architecture?", answer: "Follow AMD's tech blog and whitepapers." },
    { question: "Tell me about a time you reduced latency.", answer: "Batched small operations to reduce overhead." },
    { question: "What is your experience with heterogeneous computing?", answer: "Used both CPU and GPU for physics simulations." },
    { question: "How do you approach debugging race conditions?", answer: "Use thread sanitizers and stress testing." },
    { question: "Describe a time you learned a new API.", answer: "Learned Vulkan to build a custom renderer." },
    { question: "What is your experience with CI for hardware?", answer: "Set up automated tests for driver changes." },
    { question: "Why do you want to work in GPU computing?", answer: "Excited about accelerating AI and scientific workloads." },
    { question: "What is your long‑term career goal?", answer: "Lead a team designing next‑gen compute units." }
  ],
  salesforce: [
    { question: "Why Salesforce?", answer: "I love the culture of giving back and innovation in CRM." },
    { question: "Experience with Apex?", answer: "Built triggers and batch classes for data processing." },
    { question: "Describe a time you improved a business process.", answer: "Automated lead assignment, saving 10 hours/week." },
    { question: "What is your understanding of the Salesforce ecosystem?", answer: "Sales Cloud, Service Cloud, and AppExchange." },
    { question: "How would you improve Einstein AI?", answer: "More customisable models for specific industries." },
    { question: "Tell me about a time you integrated with external systems.", answer: "Used REST APIs to sync data between Salesforce and ERP." },
    { question: "Experience with Lightning Web Components?", answer: "Built reusable components for a customer portal." },
    { question: "How do you ensure data security in Salesforce?", answer: "Profile permissions, sharing rules, and encryption." },
    { question: "What is your experience with SOQL?", answer: "Optimised complex queries to avoid governor limits." },
    { question: "How do you handle governor limits?", answer: "Batch processing and efficient query design." },
    { question: "Describe a time you worked with the partner community.", answer: "Supported ISV partners in building managed packages." },
    { question: "What is your favourite Salesforce product?", answer: "Tableau for powerful visualisations." },
    { question: "How do you stay updated on Salesforce releases?", answer: "Follow release notes and Trailhead." },
    { question: "Tell me about a time you resolved a data inconsistency.", answer: "Used Data Loader to deduplicate records." },
    { question: "What is your experience with CI/CD for Salesforce?", answer: "Used Salesforce DX and GitHub Actions." },
    { question: "How do you approach testing in Salesforce?", answer: "Unit tests with good coverage and integration tests." },
    { question: "Describe a time you customised a standard object.", answer: "Added validation rules and flow to enforce business rules." },
    { question: "What is your experience with Heroku?", answer: "Deployed a Node.js service for real‑time events." },
    { question: "Why do you want to work in cloud CRM?", answer: "Helping businesses connect with customers is rewarding." },
    { question: "What is your long‑term career goal?", answer: "Become a Salesforce Technical Architect." }
  ],
  oracle: [
    { question: "Why Oracle?", answer: "I'm interested in enterprise database and cloud solutions." },
    { question: "Experience with PL/SQL?", answer: "Wrote stored procedures for data warehouse ETL." },
    { question: "Describe a time you optimised a query.", answer: "Added indexes and rewrote joins to reduce runtime from minutes to seconds." },
    { question: "What is your understanding of Oracle Cloud?", answer: "OCI offers IaaS, PaaS, and autonomous database." },
    { question: "How would you improve Oracle Autonomous Database?", answer: "Better integration with third‑party tools." },
    { question: "Tell me about a time you migrated a database.", answer: "Moved on‑prem Oracle to OCI with minimal downtime." },
    { question: "Experience with Real Application Clusters (RAC)?", answer: "Configured a two‑node cluster for high availability." },
    { question: "How do you ensure data integrity?", answer: "Constraints, triggers, and application‑level validation." },
    { question: "What is your experience with backup and recovery?", answer: "Used RMAN for scheduled backups and point‑in‑time recovery." },
    { question: "How do you handle large‑volume transactions?", answer: "Partition tables and use batch processing." },
    { question: "Describe a time you worked with Oracle Forms.", answer: "Maintained a legacy financial application." },
    { question: "What is your favourite Oracle product?", answer: "Oracle GoldenGate for real‑time replication." },
    { question: "How do you stay updated on Oracle tech?", answer: "Follow Oracle blogs and take OCI training." },
    { question: "Tell me about a time you resolved a deadlock.", answer: "Analysed wait events and redesigned transaction order." },
    { question: "What is your experience with Java in Oracle context?", answer: "Built stored procedures using Java inside the database." },
    { question: "How do you approach security in Oracle DB?", answer: "VPD, audit trails, and data redaction." },
    { question: "Describe a time you learned a new Oracle feature.", answer: "Used JSON support in Oracle 21c for document storage." },
    { question: "What is your experience with Oracle Enterprise Manager?", answer: "Monitored performance and set alerts." },
    { question: "Why do you want to work in enterprise databases?", answer: "Data is the core of every application." },
    { question: "What is your long‑term career goal?", answer: "Become a Database Architect." }
  ],
  ibm: [
    { question: "Why IBM?", answer: "I admire IBM's legacy in enterprise tech and AI leadership with Watson." },
    { question: "Experience with mainframes?", answer: "I've worked with z/OS and COBOL in a financial services environment." },
    { question: "What is your understanding of hybrid cloud?", answer: "IBM Cloud Pak and Red Hat OpenShift enable consistent management across on‑prem and cloud." },
    { question: "Tell me about a time you used AI to solve a problem.", answer: "I built a Watson Assistant chatbot that reduced IT support tickets by 30%." },
    { question: "How do you ensure security in a multi‑cloud environment?", answer: "Use IBM Security QRadar and consistent policy enforcement." },
    { question: "What is your experience with blockchain?", answer: "Developed a supply chain tracker using Hyperledger Fabric." },
    { question: "How do you handle large‑scale data processing?", answer: "Used Apache Spark on IBM Cloud for petabyte‑scale analytics." },
    { question: "Describe a time you led a technical project.", answer: "I coordinated a migration of legacy apps to containers." },
    { question: "What is your favourite IBM product?", answer: "Watson Studio – powerful for data science." },
    { question: "How do you stay updated on IBM tech?", answer: "Follow IBM developer blogs and complete IBM SkillsBuild courses." },
    { question: "Tell me about a time you worked with Red Hat OpenShift.", answer: "Deployed microservices and managed clusters in production." },
    { question: "What is your experience with quantum computing?", answer: "I've run simple circuits on IBM Quantum Experience." },
    { question: "How do you approach technical debt?", answer: "Regular refactoring and prioritising high‑impact areas." },
    { question: "Describe a time you had to learn a new domain quickly.", answer: "I learned financial regulations to build a compliance tool." },
    { question: "Why do you want to work in enterprise tech?", answer: "I enjoy solving large‑scale, mission‑critical problems." },
    { question: "How do you handle competing priorities?", answer: "Use a weighted scoring model and stakeholder alignment." },
    { question: "What is your experience with DevOps practices?", answer: "Built CI/CD pipelines with Jenkins and GitLab." },
    { question: "How do you ensure code maintainability?", answer: "Write clean, documented code and enforce style guides." },
    { question: "Tell me about a time you improved system reliability.", answer: "Introduced circuit breakers and retry logic to reduce outages." },
    { question: "What is your long‑term career goal?", answer: "Become a distinguished engineer and mentor next‑gen talent." }
  ],
  cisco: [
    { question: "Why Cisco?", answer: "Cisco powers the internet – I want to work on networking at scale." },
    { question: "Experience with routing protocols?", answer: "Configured OSPF and BGP in enterprise environments." },
    { question: "How would you secure a network?", answer: "Use firewalls, ACLs, 802.1X, and segment with VLANs." },
    { question: "What is your understanding of SD‑WAN?", answer: "Software‑defined WAN simplifies branch connectivity and security." },
    { question: "Tell me about a time you troubleshooted a network outage.", answer: "Isolated a spanning‑tree loop and reconfigured root bridge." },
    { question: "Experience with Cisco Identity Services Engine (ISE)?", answer: "Implemented posture assessment and guest access." },
    { question: "How do you handle zero‑day threats?", answer: "Use Cisco Talos intelligence and automate response with SecureX." },
    { question: "What is your favourite Cisco product?", answer: "Catalyst 9000 switches – programmability and security." },
    { question: "How do you stay updated on networking trends?", answer: "Follow Cisco DevNet and attend Cisco Live." },
    { question: "Describe a time you automated a network task.", answer: "Used Ansible to push ACL changes to 200 devices." },
    { question: "What is your experience with network monitoring?", answer: "Used SolarWinds and Cisco DNA Center for telemetry." },
    { question: "How do you ensure high availability?", answer: "Redundant hardware, failover protocols like HSRP, and diverse paths." },
    { question: "Tell me about a time you worked with a customer.", answer: "I helped a client redesign their campus network to improve performance." },
    { question: "What is your experience with cloud networking?", answer: "Used AWS VPC and Azure Virtual WAN, integrated with on‑prem via VPN." },
    { question: "How do you prioritise network upgrades?", answer: "Based on security vulnerabilities, capacity, and business impact." },
    { question: "Describe a time you learned a new networking technology.", answer: "Self‑studied wireless LAN controllers to redesign Wi‑Fi." },
    { question: "What is your experience with network automation tools?", answer: "Python scripts with Netmiko for device configuration." },
    { question: "How do you handle network documentation?", answer: "Keep a living repository with diagrams and configuration baselines." }
